# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20161114_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
