# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='image')),
                ('video', models.FileField(upload_to='static/videos')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
